### ISSUE TITLE
Erweiterte Informationen fürs BE Template

### ISSUE THREAD

**Issue by MrTool** [felixpfeiffer/Contao-Subcolumns#30]
Hallo,

Es wäre schon wenn im im BE Template von subcolumns noch über eine Variable die maximal anzahl bzw. die aktuell aktive spalte als integer werte hätte.

Ich werde dafür einen Pull-Request machen.

**Comment by felixpfeiffer** [comment]
Gerne!

**Comment by MrTool** [comment]
PR is draußen #31
