### ISSUE TITLE
Kann Formular mit Sicherheitsabfrage nicht absenden, wenn Spaltenset im Seitenlayout (als Modul erstellt) eingebunden ist

### ISSUE THREAD

**Issue by MacKP** [felixpfeiffer/Contao-Subcolumns#36]
Ich habe ein Spaltenset als Modul erstellt (für den Footer). Den dann im Seitenlayout eingebunden. Das Problem ist jetzt, das ich seitdem das Kontaktformular (bzw. jedes Formular, was eine Sicherheitsabfrage drinn hat nicht mehr versenden kann). Die Seite wird neu geladen und ich werde gebeten, die Sicherheitsabfrage zu beantworten.
Fehlermeldung im Log:
```
Ursprung: 	Frontend
Kategorie: 	ERROR
Benutzer: 	
Details: 	Module class "" (module "subcolumns") does not exist
Funktion: 	Contao\Controller::getFrontendModule
```
Wenn ich das Spaltenset ausblende oder das Modul deaktivire, dann geht es ohne Probleme.
Viele Grüße

**Comment by MacKP** [comment]
kommando zurück. Liegt glaube ich doch eher am Inhalt von dem Subcolumn (Fehler hatte ich jetzt auch, als ich das per Hand nachgebaut habe)... liegt glaube ich an https://github.com/hofff/contao-shariff

**Comment by felixpfeiffer** [comment]
Ähm, ja, ok. Schön das ich nicht helfen konnte :-D
